# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/romain/mam_manager/mainWin.ui'
#
# Created: Fri Mar  6 21:20:08 2015
#      by: pyside-uic 0.2.15 running on PySide 1.2.1
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(879, 622)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("images/ic_dvr_black_36dp.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setDockNestingEnabled(False)
        MainWindow.setUnifiedTitleAndToolBarOnMac(True)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("Line{\n"
"color:red;\n"
"border: 2px solid rgb(206, 206, 206);\n"
"}")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_34 = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout_34.setObjectName("verticalLayout_34")
        self.stackedWidget = QtGui.QStackedWidget(self.centralwidget)
        self.stackedWidget.setStyleSheet("QToolButton{\n"
"border:1px solid rgb(199, 199, 199);\n"
"}\n"
"QToolButton:hover{\n"
"background-color: rgb(224, 224, 224);\n"
"}\n"
"QToolButton:pressed{\n"
"background-color: rgb(171, 171, 171);\n"
"}\n"
"")
        self.stackedWidget.setObjectName("stackedWidget")
        self.page_7 = QtGui.QWidget()
        self.page_7.setObjectName("page_7")
        self.horizontalLayout_9 = QtGui.QHBoxLayout(self.page_7)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.frame = QtGui.QFrame(self.page_7)
        self.frame.setStyleSheet("QFrame{\n"
"Background-color: transparent;\n"
"}\n"
"QToolButton{\n"
"border:none;\n"
"}\n"
"\n"
"QToolButton:hover{\n"
"\n"
"border: 1px solid rgb(193, 213, 255);\n"
"background-color:qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(237, 237, 237, 255), stop:1 rgba(255, 255, 255, 255));\n"
"}\n"
"QToolButton:checked,QToolButton:pressed{\n"
"border: 1px solid blue;\n"
"background-color:qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(211, 231, 255, 255), stop:1 rgba(255, 255, 255, 255));\n"
"}")
        self.frame.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame.setLineWidth(0)
        self.frame.setObjectName("frame")
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.frame)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.b_rushes = QtGui.QToolButton(self.frame)
        self.b_rushes.setMinimumSize(QtCore.QSize(75, 75))
        self.b_rushes.setBaseSize(QtCore.QSize(0, 200))
        self.b_rushes.setIcon(icon)
        self.b_rushes.setIconSize(QtCore.QSize(50, 50))
        self.b_rushes.setCheckable(True)
        self.b_rushes.setChecked(True)
        self.b_rushes.setAutoRepeat(False)
        self.b_rushes.setAutoExclusive(True)
        self.b_rushes.setPopupMode(QtGui.QToolButton.DelayedPopup)
        self.b_rushes.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.b_rushes.setAutoRaise(False)
        self.b_rushes.setArrowType(QtCore.Qt.NoArrow)
        self.b_rushes.setObjectName("b_rushes")
        self.verticalLayout_7.addWidget(self.b_rushes)
        self.b_users = QtGui.QToolButton(self.frame)
        self.b_users.setMinimumSize(QtCore.QSize(75, 75))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("images/ic_people_black_36dp.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.b_users.setIcon(icon1)
        self.b_users.setIconSize(QtCore.QSize(50, 50))
        self.b_users.setCheckable(True)
        self.b_users.setAutoExclusive(True)
        self.b_users.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.b_users.setObjectName("b_users")
        self.verticalLayout_7.addWidget(self.b_users)
        self.b_clients = QtGui.QToolButton(self.frame)
        self.b_clients.setMinimumSize(QtCore.QSize(75, 75))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("images/ic_account_box_black_48dp.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.b_clients.setIcon(icon2)
        self.b_clients.setIconSize(QtCore.QSize(50, 50))
        self.b_clients.setCheckable(True)
        self.b_clients.setAutoExclusive(True)
        self.b_clients.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.b_clients.setObjectName("b_clients")
        self.verticalLayout_7.addWidget(self.b_clients)
        self.b_drives = QtGui.QToolButton(self.frame)
        self.b_drives.setMinimumSize(QtCore.QSize(75, 75))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("images/ic_storage_black_48dp.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.b_drives.setIcon(icon3)
        self.b_drives.setIconSize(QtCore.QSize(50, 50))
        self.b_drives.setCheckable(True)
        self.b_drives.setAutoExclusive(True)
        self.b_drives.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.b_drives.setObjectName("b_drives")
        self.verticalLayout_7.addWidget(self.b_drives)
        spacerItem = QtGui.QSpacerItem(20, 255, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem)
        self.b_progress = QtGui.QToolButton(self.frame)
        self.b_progress.setMinimumSize(QtCore.QSize(75, 75))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("images/ic_refresh_black_24dp.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.b_progress.setIcon(icon4)
        self.b_progress.setIconSize(QtCore.QSize(50, 50))
        self.b_progress.setCheckable(True)
        self.b_progress.setAutoExclusive(True)
        self.b_progress.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.b_progress.setObjectName("b_progress")
        self.verticalLayout_7.addWidget(self.b_progress)
        self.horizontalLayout_9.addWidget(self.frame)
        self.stack = QtGui.QStackedWidget(self.page_7)
        self.stack.setObjectName("stack")
        self.page = QtGui.QWidget()
        self.page.setObjectName("page")
        self.verticalLayout_19 = QtGui.QVBoxLayout(self.page)
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.splitter_2 = QtGui.QSplitter(self.page)
        self.splitter_2.setOrientation(QtCore.Qt.Vertical)
        self.splitter_2.setObjectName("splitter_2")
        self.splitter = QtGui.QSplitter(self.splitter_2)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.layoutWidget = QtGui.QWidget(self.splitter)
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_29 = QtGui.QLabel(self.layoutWidget)
        self.label_29.setFrameShadow(QtGui.QFrame.Plain)
        self.label_29.setTextFormat(QtCore.Qt.AutoText)
        self.label_29.setObjectName("label_29")
        self.verticalLayout_6.addWidget(self.label_29)
        self.collection_list = QtGui.QListView(self.layoutWidget)
        self.collection_list.setMinimumSize(QtCore.QSize(0, 0))
        self.collection_list.setMouseTracking(False)
        self.collection_list.setSelectionMode(QtGui.QAbstractItemView.ExtendedSelection)
        self.collection_list.setSelectionRectVisible(False)
        self.collection_list.setObjectName("collection_list")
        self.verticalLayout_6.addWidget(self.collection_list)
        self.horizontalLayout_14 = QtGui.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.b_add_coll = QtGui.QToolButton(self.layoutWidget)
        self.b_add_coll.setEnabled(True)
        self.b_add_coll.setAutoFillBackground(False)
        self.b_add_coll.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("images/ic_add_circle_black_48dp.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.b_add_coll.setIcon(icon5)
        self.b_add_coll.setObjectName("b_add_coll")
        self.horizontalLayout_14.addWidget(self.b_add_coll)
        self.b_remove_coll = QtGui.QToolButton(self.layoutWidget)
        self.b_remove_coll.setEnabled(False)
        self.b_remove_coll.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("images/ic_remove_circle_black_48dp.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.b_remove_coll.setIcon(icon6)
        self.b_remove_coll.setObjectName("b_remove_coll")
        self.horizontalLayout_14.addWidget(self.b_remove_coll)
        self.toolButton = QtGui.QToolButton(self.layoutWidget)
        self.toolButton.setText("")
        self.toolButton.setIcon(icon4)
        self.toolButton.setObjectName("toolButton")
        self.horizontalLayout_14.addWidget(self.toolButton)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem1)
        self.verticalLayout_6.addLayout(self.horizontalLayout_14)
        self.layoutWidget1 = QtGui.QWidget(self.splitter)
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout = QtGui.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_2 = QtGui.QLabel(self.layoutWidget1)
        self.label_2.setFrameShadow(QtGui.QFrame.Plain)
        self.label_2.setTextFormat(QtCore.Qt.AutoText)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.listView = QtGui.QListView(self.layoutWidget1)
        self.listView.setMinimumSize(QtCore.QSize(0, 0))
        self.listView.setMouseTracking(False)
        self.listView.setTabKeyNavigation(True)
        self.listView.setSelectionMode(QtGui.QAbstractItemView.ExtendedSelection)
        self.listView.setSelectionRectVisible(False)
        self.listView.setObjectName("listView")
        self.verticalLayout.addWidget(self.listView)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.b_add_gp = QtGui.QToolButton(self.layoutWidget1)
        self.b_add_gp.setEnabled(False)
        self.b_add_gp.setAutoFillBackground(False)
        self.b_add_gp.setText("")
        self.b_add_gp.setIcon(icon5)
        self.b_add_gp.setObjectName("b_add_gp")
        self.horizontalLayout.addWidget(self.b_add_gp)
        self.b_remove_gp = QtGui.QToolButton(self.layoutWidget1)
        self.b_remove_gp.setEnabled(False)
        self.b_remove_gp.setText("")
        self.b_remove_gp.setIcon(icon6)
        self.b_remove_gp.setObjectName("b_remove_gp")
        self.horizontalLayout.addWidget(self.b_remove_gp)
        self.b_chg_coll = QtGui.QToolButton(self.layoutWidget1)
        self.b_chg_coll.setEnabled(False)
        self.b_chg_coll.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("images/ic_reply_black_48dp.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.b_chg_coll.setIcon(icon7)
        self.b_chg_coll.setObjectName("b_chg_coll")
        self.horizontalLayout.addWidget(self.b_chg_coll)
        self.b_chg_rights = QtGui.QToolButton(self.layoutWidget1)
        self.b_chg_rights.setEnabled(False)
        self.b_chg_rights.setText("")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("images/ic_vpn_key_black_18dp.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.b_chg_rights.setIcon(icon8)
        self.b_chg_rights.setObjectName("b_chg_rights")
        self.horizontalLayout.addWidget(self.b_chg_rights)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.layoutWidget2 = QtGui.QWidget(self.splitter)
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.layoutWidget2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_3 = QtGui.QLabel(self.layoutWidget2)
        self.label_3.setFrameShadow(QtGui.QFrame.Plain)
        self.label_3.setTextFormat(QtCore.Qt.AutoText)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)
        self.listView_2 = QtGui.QListView(self.layoutWidget2)
        self.listView_2.setTabKeyNavigation(True)
        self.listView_2.setSelectionMode(QtGui.QAbstractItemView.ExtendedSelection)
        self.listView_2.setSelectionBehavior(QtGui.QAbstractItemView.SelectItems)
        self.listView_2.setObjectName("listView_2")
        self.verticalLayout_2.addWidget(self.listView_2)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.b_add_project = QtGui.QToolButton(self.layoutWidget2)
        self.b_add_project.setEnabled(False)
        self.b_add_project.setText("")
        self.b_add_project.setIcon(icon5)
        self.b_add_project.setObjectName("b_add_project")
        self.horizontalLayout_2.addWidget(self.b_add_project)
        self.b_rmve_project = QtGui.QToolButton(self.layoutWidget2)
        self.b_rmve_project.setEnabled(False)
        self.b_rmve_project.setText("")
        self.b_rmve_project.setIcon(icon6)
        self.b_rmve_project.setObjectName("b_rmve_project")
        self.horizontalLayout_2.addWidget(self.b_rmve_project)
        self.b_chg_gp = QtGui.QToolButton(self.layoutWidget2)
        self.b_chg_gp.setEnabled(False)
        self.b_chg_gp.setText("")
        self.b_chg_gp.setIcon(icon7)
        self.b_chg_gp.setObjectName("b_chg_gp")
        self.horizontalLayout_2.addWidget(self.b_chg_gp)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.layoutWidget3 = QtGui.QWidget(self.splitter)
        self.layoutWidget3.setObjectName("layoutWidget3")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.layoutWidget3)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_4 = QtGui.QLabel(self.layoutWidget3)
        self.label_4.setFrameShadow(QtGui.QFrame.Plain)
        self.label_4.setTextFormat(QtCore.Qt.AutoText)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_3.addWidget(self.label_4)
        self.listView_3 = QtGui.QListView(self.layoutWidget3)
        self.listView_3.setTabKeyNavigation(True)
        self.listView_3.setSelectionMode(QtGui.QAbstractItemView.ExtendedSelection)
        self.listView_3.setSelectionBehavior(QtGui.QAbstractItemView.SelectItems)
        self.listView_3.setObjectName("listView_3")
        self.verticalLayout_3.addWidget(self.listView_3)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.b_ingest = QtGui.QToolButton(self.layoutWidget3)
        self.b_ingest.setEnabled(False)
        self.b_ingest.setText("")
        self.b_ingest.setIcon(icon5)
        self.b_ingest.setObjectName("b_ingest")
        self.horizontalLayout_3.addWidget(self.b_ingest)
        self.b_card_rmve = QtGui.QToolButton(self.layoutWidget3)
        self.b_card_rmve.setEnabled(False)
        self.b_card_rmve.setText("")
        self.b_card_rmve.setIcon(icon6)
        self.b_card_rmve.setObjectName("b_card_rmve")
        self.horizontalLayout_3.addWidget(self.b_card_rmve)
        self.b_card_chge = QtGui.QToolButton(self.layoutWidget3)
        self.b_card_chge.setEnabled(False)
        self.b_card_chge.setText("")
        self.b_card_chge.setIcon(icon7)
        self.b_card_chge.setObjectName("b_card_chge")
        self.horizontalLayout_3.addWidget(self.b_card_chge)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem4)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.layoutWidget_4 = QtGui.QWidget(self.splitter)
        self.layoutWidget_4.setObjectName("layoutWidget_4")
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.layoutWidget_4)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_5 = QtGui.QLabel(self.layoutWidget_4)
        self.label_5.setFrameShadow(QtGui.QFrame.Plain)
        self.label_5.setTextFormat(QtCore.Qt.AutoText)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_4.addWidget(self.label_5)
        self.stackedWidget_3 = QtGui.QStackedWidget(self.layoutWidget_4)
        self.stackedWidget_3.setObjectName("stackedWidget_3")
        self.page_10 = QtGui.QWidget()
        self.page_10.setObjectName("page_10")
        self.verticalLayout_23 = QtGui.QVBoxLayout(self.page_10)
        self.verticalLayout_23.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_23.setObjectName("verticalLayout_23")
        self.listView_4 = QtGui.QListView(self.page_10)
        self.listView_4.setTabKeyNavigation(False)
        self.listView_4.setSelectionMode(QtGui.QAbstractItemView.ExtendedSelection)
        self.listView_4.setSelectionBehavior(QtGui.QAbstractItemView.SelectItems)
        self.listView_4.setObjectName("listView_4")
        self.verticalLayout_23.addWidget(self.listView_4)
        self.stackedWidget_3.addWidget(self.page_10)
        self.page_11 = QtGui.QWidget()
        self.page_11.setObjectName("page_11")
        self.verticalLayout_20 = QtGui.QVBoxLayout(self.page_11)
        self.verticalLayout_20.setObjectName("verticalLayout_20")
        self.label_23 = QtGui.QLabel(self.page_11)
        self.label_23.setObjectName("label_23")
        self.verticalLayout_20.addWidget(self.label_23)
        self.label_25 = QtGui.QLabel(self.page_11)
        self.label_25.setText("")
        self.label_25.setPixmap(QtGui.QPixmap("images/ic_refresh_black_24dp.png"))
        self.label_25.setAlignment(QtCore.Qt.AlignCenter)
        self.label_25.setObjectName("label_25")
        self.verticalLayout_20.addWidget(self.label_25)
        self.progressBar = QtGui.QProgressBar(self.page_11)
        self.progressBar.setMaximum(0)
        self.progressBar.setProperty("value", -1)
        self.progressBar.setObjectName("progressBar")
        self.verticalLayout_20.addWidget(self.progressBar)
        self.stackedWidget_3.addWidget(self.page_11)
        self.verticalLayout_4.addWidget(self.stackedWidget_3)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.b_add_proxy = QtGui.QToolButton(self.layoutWidget_4)
        self.b_add_proxy.setEnabled(False)
        self.b_add_proxy.setIcon(icon5)
        self.b_add_proxy.setObjectName("b_add_proxy")
        self.horizontalLayout_4.addWidget(self.b_add_proxy)
        self.b_remove_proxy = QtGui.QToolButton(self.layoutWidget_4)
        self.b_remove_proxy.setEnabled(False)
        self.b_remove_proxy.setIcon(icon6)
        self.b_remove_proxy.setObjectName("b_remove_proxy")
        self.horizontalLayout_4.addWidget(self.b_remove_proxy)
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem5)
        self.verticalLayout_4.addLayout(self.horizontalLayout_4)
        self.layoutWidget_5 = QtGui.QWidget(self.splitter_2)
        self.layoutWidget_5.setObjectName("layoutWidget_5")
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.layoutWidget_5)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label = QtGui.QLabel(self.layoutWidget_5)
        self.label.setObjectName("label")
        self.verticalLayout_5.addWidget(self.label)
        self.mdataView = QtGui.QTableView(self.layoutWidget_5)
        self.mdataView.setStyleSheet("")
        self.mdataView.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.mdataView.setShowGrid(True)
        self.mdataView.setObjectName("mdataView")
        self.mdataView.verticalHeader().setVisible(False)
        self.verticalLayout_5.addWidget(self.mdataView)
        self.verticalLayout_19.addWidget(self.splitter_2)
        self.stack.addWidget(self.page)
        self.page_2 = QtGui.QWidget()
        self.page_2.setObjectName("page_2")
        self.horizontalLayout_12 = QtGui.QHBoxLayout(self.page_2)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.stackedWidget_2 = QtGui.QStackedWidget(self.page_2)
        self.stackedWidget_2.setObjectName("stackedWidget_2")
        self.page_12 = QtGui.QWidget()
        self.page_12.setObjectName("page_12")
        self.verticalLayout_17 = QtGui.QVBoxLayout(self.page_12)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.verticalLayout_9 = QtGui.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.l_users = QtGui.QListView(self.page_12)
        self.l_users.setObjectName("l_users")
        self.verticalLayout_9.addWidget(self.l_users)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.b_add_user = QtGui.QToolButton(self.page_12)
        self.b_add_user.setEnabled(True)
        self.b_add_user.setAutoFillBackground(False)
        self.b_add_user.setText("")
        self.b_add_user.setIcon(icon5)
        self.b_add_user.setObjectName("b_add_user")
        self.horizontalLayout_6.addWidget(self.b_add_user)
        self.b_remove_user = QtGui.QToolButton(self.page_12)
        self.b_remove_user.setEnabled(False)
        self.b_remove_user.setText("")
        self.b_remove_user.setIcon(icon6)
        self.b_remove_user.setObjectName("b_remove_user")
        self.horizontalLayout_6.addWidget(self.b_remove_user)
        self.verticalLayout_9.addLayout(self.horizontalLayout_6)
        self.verticalLayout_17.addLayout(self.verticalLayout_9)
        self.stackedWidget_2.addWidget(self.page_12)
        self.page_13 = QtGui.QWidget()
        self.page_13.setObjectName("page_13")
        self.verticalLayout_18 = QtGui.QVBoxLayout(self.page_13)
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        spacerItem6 = QtGui.QSpacerItem(20, 149, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_18.addItem(spacerItem6)
        self.label_13 = QtGui.QLabel(self.page_13)
        self.label_13.setText("")
        self.label_13.setPixmap(QtGui.QPixmap("images/ic_people_black_36dp.png"))
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setObjectName("label_13")
        self.verticalLayout_18.addWidget(self.label_13)
        self.label_14 = QtGui.QLabel(self.page_13)
        self.label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_14.setObjectName("label_14")
        self.verticalLayout_18.addWidget(self.label_14)
        spacerItem7 = QtGui.QSpacerItem(20, 148, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_18.addItem(spacerItem7)
        self.stackedWidget_2.addWidget(self.page_13)
        self.horizontalLayout_12.addWidget(self.stackedWidget_2)
        self.user_stack = QtGui.QStackedWidget(self.page_2)
        self.user_stack.setObjectName("user_stack")
        self.page_3 = QtGui.QWidget()
        self.page_3.setObjectName("page_3")
        self.verticalLayout_10 = QtGui.QVBoxLayout(self.page_3)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_8 = QtGui.QLabel(self.page_3)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 0, 0, 1, 1)
        self.l_user_name = QtGui.QLineEdit(self.page_3)
        self.l_user_name.setObjectName("l_user_name")
        self.gridLayout.addWidget(self.l_user_name, 1, 0, 1, 1)
        self.label_9 = QtGui.QLabel(self.page_3)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 2, 0, 1, 1)
        self.l_user_pass1 = QtGui.QLineEdit(self.page_3)
        self.l_user_pass1.setInputMask("")
        self.l_user_pass1.setEchoMode(QtGui.QLineEdit.Password)
        self.l_user_pass1.setObjectName("l_user_pass1")
        self.gridLayout.addWidget(self.l_user_pass1, 3, 0, 1, 1)
        self.label_10 = QtGui.QLabel(self.page_3)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 4, 0, 1, 1)
        self.l_user_pass2 = QtGui.QLineEdit(self.page_3)
        self.l_user_pass2.setInputMask("")
        self.l_user_pass2.setEchoMode(QtGui.QLineEdit.Password)
        self.l_user_pass2.setObjectName("l_user_pass2")
        self.gridLayout.addWidget(self.l_user_pass2, 5, 0, 1, 1)
        self.label_11 = QtGui.QLabel(self.page_3)
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 8, 0, 1, 1)
        self.c_admin = QtGui.QComboBox(self.page_3)
        self.c_admin.setObjectName("c_admin")
        self.c_admin.addItem("")
        self.c_admin.addItem("")
        self.gridLayout.addWidget(self.c_admin, 9, 0, 1, 1)
        self.label_48 = QtGui.QLabel(self.page_3)
        self.label_48.setObjectName("label_48")
        self.gridLayout.addWidget(self.label_48, 6, 0, 1, 1)
        self.l_email = QtGui.QLineEdit(self.page_3)
        self.l_email.setObjectName("l_email")
        self.gridLayout.addWidget(self.l_email, 7, 0, 1, 1)
        self.c_masters = QtGui.QCheckBox(self.page_3)
        self.c_masters.setObjectName("c_masters")
        self.gridLayout.addWidget(self.c_masters, 11, 0, 1, 1)
        self.label_50 = QtGui.QLabel(self.page_3)
        self.label_50.setObjectName("label_50")
        self.gridLayout.addWidget(self.label_50, 12, 0, 1, 1)
        self.l_validate = QtGui.QListView(self.page_3)
        self.l_validate.setObjectName("l_validate")
        self.gridLayout.addWidget(self.l_validate, 13, 0, 1, 1)
        self.c_cansend = QtGui.QCheckBox(self.page_3)
        self.c_cansend.setObjectName("c_cansend")
        self.gridLayout.addWidget(self.c_cansend, 10, 0, 1, 1)
        self.verticalLayout_10.addLayout(self.gridLayout)
        spacerItem8 = QtGui.QSpacerItem(20, 119, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_10.addItem(spacerItem8)
        self.buttonBox = QtGui.QDialogButtonBox(self.page_3)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout_10.addWidget(self.buttonBox)
        self.user_stack.addWidget(self.page_3)
        self.page_4 = QtGui.QWidget()
        self.page_4.setObjectName("page_4")
        self.verticalLayout_8 = QtGui.QVBoxLayout(self.page_4)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        spacerItem9 = QtGui.QSpacerItem(20, 174, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_8.addItem(spacerItem9)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        spacerItem10 = QtGui.QSpacerItem(98, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem10)
        self.label_6 = QtGui.QLabel(self.page_4)
        self.label_6.setText("")
        self.label_6.setPixmap(QtGui.QPixmap("images/ic_people_black_36dp.png"))
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_7.addWidget(self.label_6)
        spacerItem11 = QtGui.QSpacerItem(98, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem11)
        self.verticalLayout_8.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        spacerItem12 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem12)
        self.label_7 = QtGui.QLabel(self.page_4)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_8.addWidget(self.label_7)
        spacerItem13 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem13)
        self.verticalLayout_8.addLayout(self.horizontalLayout_8)
        spacerItem14 = QtGui.QSpacerItem(20, 173, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_8.addItem(spacerItem14)
        self.user_stack.addWidget(self.page_4)
        self.page_9 = QtGui.QWidget()
        self.page_9.setObjectName("page_9")
        self.gridLayout_3 = QtGui.QGridLayout(self.page_9)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.ch_admin = QtGui.QCheckBox(self.page_9)
        self.ch_admin.setObjectName("ch_admin")
        self.gridLayout_3.addWidget(self.ch_admin, 6, 0, 1, 1)
        self.l_user_name_ch = QtGui.QLineEdit(self.page_9)
        self.l_user_name_ch.setEnabled(False)
        self.l_user_name_ch.setObjectName("l_user_name_ch")
        self.gridLayout_3.addWidget(self.l_user_name_ch, 1, 0, 1, 1)
        self.label_21 = QtGui.QLabel(self.page_9)
        self.label_21.setObjectName("label_21")
        self.gridLayout_3.addWidget(self.label_21, 2, 0, 1, 1)
        self.chl_mail = QtGui.QLineEdit(self.page_9)
        self.chl_mail.setObjectName("chl_mail")
        self.gridLayout_3.addWidget(self.chl_mail, 5, 0, 1, 1)
        self.buttonBox_2 = QtGui.QDialogButtonBox(self.page_9)
        self.buttonBox_2.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox_2.setObjectName("buttonBox_2")
        self.gridLayout_3.addWidget(self.buttonBox_2, 12, 0, 1, 1)
        self.label_22 = QtGui.QLabel(self.page_9)
        self.label_22.setObjectName("label_22")
        self.gridLayout_3.addWidget(self.label_22, 9, 0, 1, 1)
        self.ch_master = QtGui.QCheckBox(self.page_9)
        self.ch_master.setObjectName("ch_master")
        self.gridLayout_3.addWidget(self.ch_master, 8, 0, 1, 1)
        self.label_20 = QtGui.QLabel(self.page_9)
        self.label_20.setObjectName("label_20")
        self.gridLayout_3.addWidget(self.label_20, 0, 0, 1, 1)
        self.label_24 = QtGui.QLabel(self.page_9)
        self.label_24.setObjectName("label_24")
        self.gridLayout_3.addWidget(self.label_24, 4, 0, 1, 1)
        self.horizontalLayout_19 = QtGui.QHBoxLayout()
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.l_user_pass_ch = QtGui.QLineEdit(self.page_9)
        self.l_user_pass_ch.setEnabled(False)
        self.l_user_pass_ch.setEchoMode(QtGui.QLineEdit.Password)
        self.l_user_pass_ch.setObjectName("l_user_pass_ch")
        self.horizontalLayout_19.addWidget(self.l_user_pass_ch)
        self.change_pass = QtGui.QToolButton(self.page_9)
        self.change_pass.setObjectName("change_pass")
        self.horizontalLayout_19.addWidget(self.change_pass)
        self.gridLayout_3.addLayout(self.horizontalLayout_19, 3, 0, 1, 1)
        self.ch_validate = QtGui.QListView(self.page_9)
        self.ch_validate.setObjectName("ch_validate")
        self.gridLayout_3.addWidget(self.ch_validate, 10, 0, 1, 1)
        spacerItem15 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem15, 11, 0, 1, 1)
        self.ch_send = QtGui.QCheckBox(self.page_9)
        self.ch_send.setObjectName("ch_send")
        self.gridLayout_3.addWidget(self.ch_send, 7, 0, 1, 1)
        self.user_stack.addWidget(self.page_9)
        self.horizontalLayout_12.addWidget(self.user_stack)
        self.stack.addWidget(self.page_2)
        self.page_5 = QtGui.QWidget()
        self.page_5.setObjectName("page_5")
        self.horizontalLayout_11 = QtGui.QHBoxLayout(self.page_5)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.verticalLayout_13 = QtGui.QVBoxLayout()
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        spacerItem16 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_13.addItem(spacerItem16)
        self.webView = QtWebKit.QWebView(self.page_5)
        self.webView.setAutoFillBackground(False)
        self.webView.setStyleSheet("background-color: rgb(207, 207, 207);")
        self.webView.setObjectName("webView")
        self.verticalLayout_13.addWidget(self.webView)
        spacerItem17 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_13.addItem(spacerItem17)
        self.verticalLayout_11 = QtGui.QVBoxLayout()
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.label_12 = QtGui.QLabel(self.page_5)
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.verticalLayout_11.addWidget(self.label_12)
        self.asset_disk_name_label = QtGui.QLabel(self.page_5)
        self.asset_disk_name_label.setAlignment(QtCore.Qt.AlignCenter)
        self.asset_disk_name_label.setObjectName("asset_disk_name_label")
        self.verticalLayout_11.addWidget(self.asset_disk_name_label)
        self.asset_disk_free_label = QtGui.QLabel(self.page_5)
        self.asset_disk_free_label.setAlignment(QtCore.Qt.AlignCenter)
        self.asset_disk_free_label.setObjectName("asset_disk_free_label")
        self.verticalLayout_11.addWidget(self.asset_disk_free_label)
        self.asset_disk_online_label = QtGui.QLabel(self.page_5)
        self.asset_disk_online_label.setAlignment(QtCore.Qt.AlignCenter)
        self.asset_disk_online_label.setObjectName("asset_disk_online_label")
        self.verticalLayout_11.addWidget(self.asset_disk_online_label)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem18 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem18)
        self.asset_disk_change = QtGui.QToolButton(self.page_5)
        self.asset_disk_change.setIcon(icon5)
        self.asset_disk_change.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.asset_disk_change.setObjectName("asset_disk_change")
        self.horizontalLayout_5.addWidget(self.asset_disk_change)
        self.asset_disk_update = QtGui.QToolButton(self.page_5)
        self.asset_disk_update.setIcon(icon4)
        self.asset_disk_update.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.asset_disk_update.setObjectName("asset_disk_update")
        self.horizontalLayout_5.addWidget(self.asset_disk_update)
        spacerItem19 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem19)
        self.verticalLayout_11.addLayout(self.horizontalLayout_5)
        self.verticalLayout_13.addLayout(self.verticalLayout_11)
        self.horizontalLayout_11.addLayout(self.verticalLayout_13)
        self.verticalLayout_14 = QtGui.QVBoxLayout()
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        spacerItem20 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_14.addItem(spacerItem20)
        self.webView_2 = QtWebKit.QWebView(self.page_5)
        self.webView_2.setAutoFillBackground(False)
        self.webView_2.setStyleSheet("background-color: rgb(207, 207, 207);")
        self.webView_2.setProperty("url", QtCore.QUrl("about:blank"))
        self.webView_2.setObjectName("webView_2")
        self.verticalLayout_14.addWidget(self.webView_2)
        spacerItem21 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_14.addItem(spacerItem21)
        self.verticalLayout_12 = QtGui.QVBoxLayout()
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.label_15 = QtGui.QLabel(self.page_5)
        self.label_15.setAlignment(QtCore.Qt.AlignCenter)
        self.label_15.setObjectName("label_15")
        self.verticalLayout_12.addWidget(self.label_15)
        self.proxy_disk_name_label = QtGui.QLabel(self.page_5)
        self.proxy_disk_name_label.setAlignment(QtCore.Qt.AlignCenter)
        self.proxy_disk_name_label.setObjectName("proxy_disk_name_label")
        self.verticalLayout_12.addWidget(self.proxy_disk_name_label)
        self.proxy_disk_free_label = QtGui.QLabel(self.page_5)
        self.proxy_disk_free_label.setAlignment(QtCore.Qt.AlignCenter)
        self.proxy_disk_free_label.setObjectName("proxy_disk_free_label")
        self.verticalLayout_12.addWidget(self.proxy_disk_free_label)
        self.proxy_disk_free_label_2 = QtGui.QLabel(self.page_5)
        self.proxy_disk_free_label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.proxy_disk_free_label_2.setObjectName("proxy_disk_free_label_2")
        self.verticalLayout_12.addWidget(self.proxy_disk_free_label_2)
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        spacerItem22 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem22)
        self.proxy_disk_change = QtGui.QToolButton(self.page_5)
        self.proxy_disk_change.setIcon(icon5)
        self.proxy_disk_change.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.proxy_disk_change.setObjectName("proxy_disk_change")
        self.horizontalLayout_10.addWidget(self.proxy_disk_change)
        spacerItem23 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem23)
        self.verticalLayout_12.addLayout(self.horizontalLayout_10)
        self.verticalLayout_14.addLayout(self.verticalLayout_12)
        self.horizontalLayout_11.addLayout(self.verticalLayout_14)
        self.stack.addWidget(self.page_5)
        self.page_6 = QtGui.QWidget()
        self.page_6.setObjectName("page_6")
        self.gridLayout_9 = QtGui.QGridLayout(self.page_6)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.verticalLayout_60 = QtGui.QVBoxLayout()
        self.verticalLayout_60.setObjectName("verticalLayout_60")
        self.label_86 = QtGui.QLabel(self.page_6)
        self.label_86.setText("")
        self.label_86.setPixmap(QtGui.QPixmap("images/ic_swap_horiz_black_48dp.png"))
        self.label_86.setAlignment(QtCore.Qt.AlignCenter)
        self.label_86.setObjectName("label_86")
        self.verticalLayout_60.addWidget(self.label_86)
        self.label_26 = QtGui.QLabel(self.page_6)
        self.label_26.setAlignment(QtCore.Qt.AlignCenter)
        self.label_26.setObjectName("label_26")
        self.verticalLayout_60.addWidget(self.label_26)
        self.gridLayout_9.addLayout(self.verticalLayout_60, 0, 0, 1, 1)
        self.sc_analyse = QtGui.QScrollArea(self.page_6)
        self.sc_analyse.setWidgetResizable(True)
        self.sc_analyse.setObjectName("sc_analyse")
        self.scrollAreaWidgetContents = QtGui.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 565, 144))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_15 = QtGui.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.lab_analyse = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.lab_analyse.setObjectName("lab_analyse")
        self.verticalLayout_15.addWidget(self.lab_analyse)
        self.sc_analyse.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout_9.addWidget(self.sc_analyse, 0, 2, 1, 1)
        self.verticalLayout_61 = QtGui.QVBoxLayout()
        self.verticalLayout_61.setObjectName("verticalLayout_61")
        self.label_87 = QtGui.QLabel(self.page_6)
        self.label_87.setText("")
        self.label_87.setPixmap(QtGui.QPixmap("images/ic_storage_black_.png"))
        self.label_87.setAlignment(QtCore.Qt.AlignCenter)
        self.label_87.setObjectName("label_87")
        self.verticalLayout_61.addWidget(self.label_87)
        self.label_27 = QtGui.QLabel(self.page_6)
        self.label_27.setAlignment(QtCore.Qt.AlignCenter)
        self.label_27.setObjectName("label_27")
        self.verticalLayout_61.addWidget(self.label_27)
        self.gridLayout_9.addLayout(self.verticalLayout_61, 1, 0, 1, 1)
        self.sc_copy = QtGui.QScrollArea(self.page_6)
        self.sc_copy.setWidgetResizable(True)
        self.sc_copy.setObjectName("sc_copy")
        self.scrollAreaWidgetContents_2 = QtGui.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 565, 144))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.verticalLayout_21 = QtGui.QVBoxLayout(self.scrollAreaWidgetContents_2)
        self.verticalLayout_21.setObjectName("verticalLayout_21")
        self.lab_copy = QtGui.QLabel(self.scrollAreaWidgetContents_2)
        self.lab_copy.setObjectName("lab_copy")
        self.verticalLayout_21.addWidget(self.lab_copy)
        self.sc_copy.setWidget(self.scrollAreaWidgetContents_2)
        self.gridLayout_9.addWidget(self.sc_copy, 1, 2, 1, 1)
        self.verticalLayout_62 = QtGui.QVBoxLayout()
        self.verticalLayout_62.setObjectName("verticalLayout_62")
        self.label_88 = QtGui.QLabel(self.page_6)
        self.label_88.setText("")
        self.label_88.setPixmap(QtGui.QPixmap("images/ic_video_collection_black_48dp.png"))
        self.label_88.setAlignment(QtCore.Qt.AlignCenter)
        self.label_88.setObjectName("label_88")
        self.verticalLayout_62.addWidget(self.label_88)
        self.label_28 = QtGui.QLabel(self.page_6)
        self.label_28.setAlignment(QtCore.Qt.AlignCenter)
        self.label_28.setObjectName("label_28")
        self.verticalLayout_62.addWidget(self.label_28)
        self.gridLayout_9.addLayout(self.verticalLayout_62, 2, 0, 1, 1)
        self.sc_proxy = QtGui.QScrollArea(self.page_6)
        self.sc_proxy.setWidgetResizable(True)
        self.sc_proxy.setObjectName("sc_proxy")
        self.scrollAreaWidgetContents_3 = QtGui.QWidget()
        self.scrollAreaWidgetContents_3.setGeometry(QtCore.QRect(0, 0, 565, 144))
        self.scrollAreaWidgetContents_3.setObjectName("scrollAreaWidgetContents_3")
        self.verticalLayout_22 = QtGui.QVBoxLayout(self.scrollAreaWidgetContents_3)
        self.verticalLayout_22.setObjectName("verticalLayout_22")
        self.lab_proxy = QtGui.QLabel(self.scrollAreaWidgetContents_3)
        self.lab_proxy.setObjectName("lab_proxy")
        self.verticalLayout_22.addWidget(self.lab_proxy)
        self.sc_proxy.setWidget(self.scrollAreaWidgetContents_3)
        self.gridLayout_9.addWidget(self.sc_proxy, 2, 2, 1, 1)
        self.lto_progress = QtGui.QProgressBar(self.page_6)
        self.lto_progress.setProperty("value", 100)
        self.lto_progress.setObjectName("lto_progress")
        self.gridLayout_9.addWidget(self.lto_progress, 4, 2, 1, 1)
        self.label_42 = QtGui.QLabel(self.page_6)
        self.label_42.setObjectName("label_42")
        self.gridLayout_9.addWidget(self.label_42, 4, 0, 1, 1)
        self.label_49 = QtGui.QLabel(self.page_6)
        self.label_49.setObjectName("label_49")
        self.gridLayout_9.addWidget(self.label_49, 3, 2, 1, 1)
        self.stack.addWidget(self.page_6)
        self.page_14 = QtGui.QWidget()
        self.page_14.setObjectName("page_14")
        self.horizontalLayout_20 = QtGui.QHBoxLayout(self.page_14)
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.stackedWidget_4 = QtGui.QStackedWidget(self.page_14)
        self.stackedWidget_4.setObjectName("stackedWidget_4")
        self.page_17 = QtGui.QWidget()
        self.page_17.setObjectName("page_17")
        self.verticalLayout_27 = QtGui.QVBoxLayout(self.page_17)
        self.verticalLayout_27.setObjectName("verticalLayout_27")
        self.verticalLayout_28 = QtGui.QVBoxLayout()
        self.verticalLayout_28.setObjectName("verticalLayout_28")
        self.l_client = QtGui.QListView(self.page_17)
        self.l_client.setObjectName("l_client")
        self.verticalLayout_28.addWidget(self.l_client)
        self.horizontalLayout_16 = QtGui.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.b_add_client = QtGui.QToolButton(self.page_17)
        self.b_add_client.setEnabled(True)
        self.b_add_client.setAutoFillBackground(False)
        self.b_add_client.setText("")
        self.b_add_client.setIcon(icon5)
        self.b_add_client.setObjectName("b_add_client")
        self.horizontalLayout_16.addWidget(self.b_add_client)
        self.b_remove_user_3 = QtGui.QToolButton(self.page_17)
        self.b_remove_user_3.setEnabled(False)
        self.b_remove_user_3.setText("")
        self.b_remove_user_3.setIcon(icon6)
        self.b_remove_user_3.setObjectName("b_remove_user_3")
        self.horizontalLayout_16.addWidget(self.b_remove_user_3)
        self.verticalLayout_28.addLayout(self.horizontalLayout_16)
        self.verticalLayout_27.addLayout(self.verticalLayout_28)
        self.stackedWidget_4.addWidget(self.page_17)
        self.page_18 = QtGui.QWidget()
        self.page_18.setObjectName("page_18")
        self.verticalLayout_29 = QtGui.QVBoxLayout(self.page_18)
        self.verticalLayout_29.setObjectName("verticalLayout_29")
        spacerItem24 = QtGui.QSpacerItem(20, 149, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_29.addItem(spacerItem24)
        self.label_33 = QtGui.QLabel(self.page_18)
        self.label_33.setText("")
        self.label_33.setPixmap(QtGui.QPixmap("images/ic_account_box_black_48dp.png"))
        self.label_33.setAlignment(QtCore.Qt.AlignCenter)
        self.label_33.setObjectName("label_33")
        self.verticalLayout_29.addWidget(self.label_33)
        self.label_34 = QtGui.QLabel(self.page_18)
        self.label_34.setAlignment(QtCore.Qt.AlignCenter)
        self.label_34.setObjectName("label_34")
        self.verticalLayout_29.addWidget(self.label_34)
        spacerItem25 = QtGui.QSpacerItem(20, 148, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_29.addItem(spacerItem25)
        self.stackedWidget_4.addWidget(self.page_18)
        self.horizontalLayout_20.addWidget(self.stackedWidget_4)
        self.user_stack_2 = QtGui.QStackedWidget(self.page_14)
        self.user_stack_2.setObjectName("user_stack_2")
        self.page_19 = QtGui.QWidget()
        self.page_19.setObjectName("page_19")
        self.verticalLayout_30 = QtGui.QVBoxLayout(self.page_19)
        self.verticalLayout_30.setObjectName("verticalLayout_30")
        self.gridLayout_4 = QtGui.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.l_client_groups = QtGui.QListView(self.page_19)
        self.l_client_groups.setObjectName("l_client_groups")
        self.gridLayout_4.addWidget(self.l_client_groups, 13, 0, 1, 1)
        self.label_37 = QtGui.QLabel(self.page_19)
        self.label_37.setObjectName("label_37")
        self.gridLayout_4.addWidget(self.label_37, 6, 0, 1, 1)
        self.label_38 = QtGui.QLabel(self.page_19)
        self.label_38.setObjectName("label_38")
        self.gridLayout_4.addWidget(self.label_38, 10, 0, 1, 1)
        self.l_client__pass1 = QtGui.QLineEdit(self.page_19)
        self.l_client__pass1.setInputMask("")
        self.l_client__pass1.setEchoMode(QtGui.QLineEdit.Password)
        self.l_client__pass1.setObjectName("l_client__pass1")
        self.gridLayout_4.addWidget(self.l_client__pass1, 5, 0, 1, 1)
        self.label_35 = QtGui.QLabel(self.page_19)
        self.label_35.setObjectName("label_35")
        self.gridLayout_4.addWidget(self.label_35, 0, 0, 1, 1)
        self.label_36 = QtGui.QLabel(self.page_19)
        self.label_36.setObjectName("label_36")
        self.gridLayout_4.addWidget(self.label_36, 4, 0, 1, 1)
        self.l_client_name = QtGui.QLineEdit(self.page_19)
        self.l_client_name.setObjectName("l_client_name")
        self.gridLayout_4.addWidget(self.l_client_name, 1, 0, 1, 1)
        self.l_client_pass2 = QtGui.QLineEdit(self.page_19)
        self.l_client_pass2.setInputMask("")
        self.l_client_pass2.setEchoMode(QtGui.QLineEdit.Password)
        self.l_client_pass2.setObjectName("l_client_pass2")
        self.gridLayout_4.addWidget(self.l_client_pass2, 7, 0, 1, 1)
        self.l_client_mail = QtGui.QLineEdit(self.page_19)
        self.l_client_mail.setObjectName("l_client_mail")
        self.gridLayout_4.addWidget(self.l_client_mail, 11, 0, 1, 1)
        self.label_47 = QtGui.QLabel(self.page_19)
        self.label_47.setObjectName("label_47")
        self.gridLayout_4.addWidget(self.label_47, 12, 0, 1, 1)
        self.label_41 = QtGui.QLabel(self.page_19)
        self.label_41.setObjectName("label_41")
        self.gridLayout_4.addWidget(self.label_41, 8, 0, 1, 1)
        self.l_client_company = QtGui.QLineEdit(self.page_19)
        self.l_client_company.setObjectName("l_client_company")
        self.gridLayout_4.addWidget(self.l_client_company, 9, 0, 1, 1)
        self.label_32 = QtGui.QLabel(self.page_19)
        self.label_32.setObjectName("label_32")
        self.gridLayout_4.addWidget(self.label_32, 2, 0, 1, 1)
        self.l_client_fullName = QtGui.QLineEdit(self.page_19)
        self.l_client_fullName.setObjectName("l_client_fullName")
        self.gridLayout_4.addWidget(self.l_client_fullName, 3, 0, 1, 1)
        self.verticalLayout_30.addLayout(self.gridLayout_4)
        spacerItem26 = QtGui.QSpacerItem(20, 119, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_30.addItem(spacerItem26)
        self.buttonBox_3 = QtGui.QDialogButtonBox(self.page_19)
        self.buttonBox_3.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox_3.setObjectName("buttonBox_3")
        self.verticalLayout_30.addWidget(self.buttonBox_3)
        self.user_stack_2.addWidget(self.page_19)
        self.page_20 = QtGui.QWidget()
        self.page_20.setObjectName("page_20")
        self.verticalLayout_35 = QtGui.QVBoxLayout(self.page_20)
        self.verticalLayout_35.setObjectName("verticalLayout_35")
        spacerItem27 = QtGui.QSpacerItem(20, 174, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_35.addItem(spacerItem27)
        self.horizontalLayout_17 = QtGui.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        spacerItem28 = QtGui.QSpacerItem(98, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_17.addItem(spacerItem28)
        self.label_39 = QtGui.QLabel(self.page_20)
        self.label_39.setText("")
        self.label_39.setPixmap(QtGui.QPixmap("images/ic_account_box_black_48dp.png"))
        self.label_39.setObjectName("label_39")
        self.horizontalLayout_17.addWidget(self.label_39)
        spacerItem29 = QtGui.QSpacerItem(98, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_17.addItem(spacerItem29)
        self.verticalLayout_35.addLayout(self.horizontalLayout_17)
        self.horizontalLayout_18 = QtGui.QHBoxLayout()
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        spacerItem30 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_18.addItem(spacerItem30)
        self.label_40 = QtGui.QLabel(self.page_20)
        self.label_40.setObjectName("label_40")
        self.horizontalLayout_18.addWidget(self.label_40)
        spacerItem31 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_18.addItem(spacerItem31)
        self.verticalLayout_35.addLayout(self.horizontalLayout_18)
        spacerItem32 = QtGui.QSpacerItem(20, 173, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_35.addItem(spacerItem32)
        self.user_stack_2.addWidget(self.page_20)
        self.page_21 = QtGui.QWidget()
        self.page_21.setObjectName("page_21")
        self.verticalLayout_24 = QtGui.QVBoxLayout(self.page_21)
        self.verticalLayout_24.setObjectName("verticalLayout_24")
        self.gridLayout_6 = QtGui.QGridLayout()
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.label_44 = QtGui.QLabel(self.page_21)
        self.label_44.setObjectName("label_44")
        self.gridLayout_6.addWidget(self.label_44, 0, 0, 1, 1)
        self.lineEdit = QtGui.QLineEdit(self.page_21)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout_6.addWidget(self.lineEdit, 9, 0, 1, 1)
        self.l_user_name_ch_2 = QtGui.QLineEdit(self.page_21)
        self.l_user_name_ch_2.setObjectName("l_user_name_ch_2")
        self.gridLayout_6.addWidget(self.l_user_name_ch_2, 1, 0, 1, 1)
        self.label_45 = QtGui.QLabel(self.page_21)
        self.label_45.setObjectName("label_45")
        self.gridLayout_6.addWidget(self.label_45, 8, 0, 1, 1)
        self.label_43 = QtGui.QLabel(self.page_21)
        self.label_43.setObjectName("label_43")
        self.gridLayout_6.addWidget(self.label_43, 4, 0, 1, 1)
        self.label_46 = QtGui.QLabel(self.page_21)
        self.label_46.setObjectName("label_46")
        self.gridLayout_6.addWidget(self.label_46, 10, 0, 1, 1)
        self.horizontalLayout_15 = QtGui.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.l_user_pass1_ch_2 = QtGui.QLineEdit(self.page_21)
        self.l_user_pass1_ch_2.setEnabled(False)
        self.l_user_pass1_ch_2.setInputMask("")
        self.l_user_pass1_ch_2.setText("")
        self.l_user_pass1_ch_2.setEchoMode(QtGui.QLineEdit.Password)
        self.l_user_pass1_ch_2.setPlaceholderText("")
        self.l_user_pass1_ch_2.setObjectName("l_user_pass1_ch_2")
        self.horizontalLayout_15.addWidget(self.l_user_pass1_ch_2)
        self.toolButton_2 = QtGui.QToolButton(self.page_21)
        self.toolButton_2.setObjectName("toolButton_2")
        self.horizontalLayout_15.addWidget(self.toolButton_2)
        self.gridLayout_6.addLayout(self.horizontalLayout_15, 5, 0, 1, 1)
        self.lineEdit_3 = QtGui.QLineEdit(self.page_21)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.gridLayout_6.addWidget(self.lineEdit_3, 3, 0, 1, 1)
        self.label_30 = QtGui.QLabel(self.page_21)
        self.label_30.setObjectName("label_30")
        self.gridLayout_6.addWidget(self.label_30, 2, 0, 1, 1)
        self.lineEdit_4 = QtGui.QLineEdit(self.page_21)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.gridLayout_6.addWidget(self.lineEdit_4, 7, 0, 1, 1)
        self.label_31 = QtGui.QLabel(self.page_21)
        self.label_31.setObjectName("label_31")
        self.gridLayout_6.addWidget(self.label_31, 6, 0, 1, 1)
        self.l_groups = QtGui.QListView(self.page_21)
        self.l_groups.setObjectName("l_groups")
        self.gridLayout_6.addWidget(self.l_groups, 11, 0, 1, 1)
        self.verticalLayout_24.addLayout(self.gridLayout_6)
        spacerItem33 = QtGui.QSpacerItem(20, 0, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_24.addItem(spacerItem33)
        self.buttonBox_4 = QtGui.QDialogButtonBox(self.page_21)
        self.buttonBox_4.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox_4.setObjectName("buttonBox_4")
        self.verticalLayout_24.addWidget(self.buttonBox_4)
        self.user_stack_2.addWidget(self.page_21)
        self.horizontalLayout_20.addWidget(self.user_stack_2)
        self.stack.addWidget(self.page_14)
        self.horizontalLayout_9.addWidget(self.stack)
        self.stackedWidget.addWidget(self.page_7)
        self.page_8 = QtGui.QWidget()
        self.page_8.setObjectName("page_8")
        self.verticalLayout_33 = QtGui.QVBoxLayout(self.page_8)
        self.verticalLayout_33.setObjectName("verticalLayout_33")
        self.verticalLayout_32 = QtGui.QVBoxLayout()
        self.verticalLayout_32.setObjectName("verticalLayout_32")
        self.label_18 = QtGui.QLabel(self.page_8)
        self.label_18.setText("")
        self.label_18.setPixmap(QtGui.QPixmap("images/ic_people_black_36dp.png"))
        self.label_18.setAlignment(QtCore.Qt.AlignCenter)
        self.label_18.setObjectName("label_18")
        self.verticalLayout_32.addWidget(self.label_18)
        self.label_19 = QtGui.QLabel(self.page_8)
        self.label_19.setAlignment(QtCore.Qt.AlignCenter)
        self.label_19.setObjectName("label_19")
        self.verticalLayout_32.addWidget(self.label_19)
        self.verticalLayout_33.addLayout(self.verticalLayout_32)
        self.verticalLayout_31 = QtGui.QVBoxLayout()
        self.verticalLayout_31.setObjectName("verticalLayout_31")
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_17 = QtGui.QLabel(self.page_8)
        self.label_17.setObjectName("label_17")
        self.gridLayout_2.addWidget(self.label_17, 2, 0, 1, 1)
        self.l_pass = QtGui.QLineEdit(self.page_8)
        self.l_pass.setEchoMode(QtGui.QLineEdit.Password)
        self.l_pass.setObjectName("l_pass")
        self.gridLayout_2.addWidget(self.l_pass, 2, 1, 1, 1)
        self.l_user = QtGui.QLineEdit(self.page_8)
        self.l_user.setObjectName("l_user")
        self.gridLayout_2.addWidget(self.l_user, 1, 1, 1, 1)
        self.label_16 = QtGui.QLabel(self.page_8)
        self.label_16.setObjectName("label_16")
        self.gridLayout_2.addWidget(self.label_16, 1, 0, 1, 1)
        spacerItem34 = QtGui.QSpacerItem(20, 60, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem34, 0, 1, 1, 1)
        self.horizontalLayout_24 = QtGui.QHBoxLayout()
        self.horizontalLayout_24.setObjectName("horizontalLayout_24")
        self.toolButton_7 = QtGui.QToolButton(self.page_8)
        self.toolButton_7.setIcon(icon4)
        self.toolButton_7.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.toolButton_7.setObjectName("toolButton_7")
        self.horizontalLayout_24.addWidget(self.toolButton_7)
        spacerItem35 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_24.addItem(spacerItem35)
        self.b_connect = QtGui.QToolButton(self.page_8)
        self.b_connect.setEnabled(False)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap("images/ic_play_circle_fill_black_24dp.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.b_connect.setIcon(icon9)
        self.b_connect.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.b_connect.setObjectName("b_connect")
        self.horizontalLayout_24.addWidget(self.b_connect)
        self.gridLayout_2.addLayout(self.horizontalLayout_24, 3, 1, 1, 1)
        self.verticalLayout_31.addLayout(self.gridLayout_2)
        self.verticalLayout_33.addLayout(self.verticalLayout_31)
        self.gridLayout_5 = QtGui.QGridLayout()
        self.gridLayout_5.setSizeConstraint(QtGui.QLayout.SetFixedSize)
        self.gridLayout_5.setObjectName("gridLayout_5")
        spacerItem36 = QtGui.QSpacerItem(20, 60, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_5.addItem(spacerItem36, 0, 2, 1, 1)
        spacerItem37 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem37, 1, 3, 1, 1)
        self.dbIcon = QtGui.QToolButton(self.page_8)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap("images/ic_error_red_48dp.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.dbIcon.setIcon(icon10)
        self.dbIcon.setPopupMode(QtGui.QToolButton.InstantPopup)
        self.dbIcon.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.dbIcon.setObjectName("dbIcon")
        self.gridLayout_5.addWidget(self.dbIcon, 1, 1, 1, 1)
        self.verticalLayout_33.addLayout(self.gridLayout_5)
        self.stackedWidget.addWidget(self.page_8)
        self.verticalLayout_34.addWidget(self.stackedWidget)
        self.deconnect = QtGui.QLabel(self.centralwidget)
        self.deconnect.setObjectName("deconnect")
        self.verticalLayout_34.addWidget(self.deconnect)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 879, 25))
        self.menubar.setObjectName("menubar")
        self.menuFichier = QtGui.QMenu(self.menubar)
        self.menuFichier.setObjectName("menuFichier")
        self.menuActions_de_l_administrateur = QtGui.QMenu(self.menubar)
        self.menuActions_de_l_administrateur.setObjectName("menuActions_de_l_administrateur")
        self.menuOutils = QtGui.QMenu(self.menubar)
        self.menuOutils.setObjectName("menuOutils")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionQuitter = QtGui.QAction(MainWindow)
        self.actionQuitter.setObjectName("actionQuitter")
        self.actionPurger_les_miniatures = QtGui.QAction(MainWindow)
        self.actionPurger_les_miniatures.setObjectName("actionPurger_les_miniatures")
        self.actionEchec_proxy = QtGui.QAction(MainWindow)
        self.actionEchec_proxy.setObjectName("actionEchec_proxy")
        self.sendmailToUsers = QtGui.QAction(MainWindow)
        self.sendmailToUsers.setObjectName("sendmailToUsers")
        self.sendmailToClients = QtGui.QAction(MainWindow)
        self.sendmailToClients.setObjectName("sendmailToClients")
        self.sendmailToDevel = QtGui.QAction(MainWindow)
        self.sendmailToDevel.setObjectName("sendmailToDevel")
        self.menuFichier.addAction(self.actionQuitter)
        self.menuFichier.addSeparator()
        self.menuActions_de_l_administrateur.addAction(self.actionPurger_les_miniatures)
        self.menuActions_de_l_administrateur.addSeparator()
        self.menuOutils.addAction(self.sendmailToUsers)
        self.menuOutils.addAction(self.sendmailToClients)
        self.menuOutils.addSeparator()
        self.menuOutils.addAction(self.sendmailToDevel)
        self.menubar.addAction(self.menuFichier.menuAction())
        self.menubar.addAction(self.menuActions_de_l_administrateur.menuAction())
        self.menubar.addAction(self.menuOutils.menuAction())

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(1)
        self.stack.setCurrentIndex(0)
        self.stackedWidget_3.setCurrentIndex(0)
        self.stackedWidget_2.setCurrentIndex(0)
        self.user_stack.setCurrentIndex(1)
        self.stackedWidget_4.setCurrentIndex(0)
        self.user_stack_2.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.l_user, self.l_pass)
        MainWindow.setTabOrder(self.l_pass, self.listView_2)
        MainWindow.setTabOrder(self.listView_2, self.b_add_project)
        MainWindow.setTabOrder(self.b_add_project, self.b_rmve_project)
        MainWindow.setTabOrder(self.b_rmve_project, self.b_chg_gp)
        MainWindow.setTabOrder(self.b_chg_gp, self.listView_3)
        MainWindow.setTabOrder(self.listView_3, self.b_ingest)
        MainWindow.setTabOrder(self.b_ingest, self.b_card_rmve)
        MainWindow.setTabOrder(self.b_card_rmve, self.b_card_chge)
        MainWindow.setTabOrder(self.b_card_chge, self.b_add_proxy)
        MainWindow.setTabOrder(self.b_add_proxy, self.b_remove_proxy)
        MainWindow.setTabOrder(self.b_remove_proxy, self.mdataView)
        MainWindow.setTabOrder(self.mdataView, self.b_add_user)
        MainWindow.setTabOrder(self.b_add_user, self.b_remove_user)
        MainWindow.setTabOrder(self.b_remove_user, self.l_user_name)
        MainWindow.setTabOrder(self.l_user_name, self.l_user_pass1)
        MainWindow.setTabOrder(self.l_user_pass1, self.l_user_pass2)
        MainWindow.setTabOrder(self.l_user_pass2, self.c_admin)
        MainWindow.setTabOrder(self.c_admin, self.webView)
        MainWindow.setTabOrder(self.webView, self.asset_disk_change)
        MainWindow.setTabOrder(self.asset_disk_change, self.webView_2)
        MainWindow.setTabOrder(self.webView_2, self.b_users)
        MainWindow.setTabOrder(self.b_users, self.b_rushes)
        MainWindow.setTabOrder(self.b_rushes, self.b_progress)
        MainWindow.setTabOrder(self.b_progress, self.b_drives)
        MainWindow.setTabOrder(self.b_drives, self.dbIcon)
        MainWindow.setTabOrder(self.dbIcon, self.l_user_name_ch)
        MainWindow.setTabOrder(self.l_user_name_ch, self.b_connect)
        MainWindow.setTabOrder(self.b_connect, self.toolButton_7)
        MainWindow.setTabOrder(self.toolButton_7, self.l_user_pass_ch)
        MainWindow.setTabOrder(self.l_user_pass_ch, self.buttonBox)
        MainWindow.setTabOrder(self.buttonBox, self.buttonBox_2)
        MainWindow.setTabOrder(self.buttonBox_2, self.asset_disk_update)
        MainWindow.setTabOrder(self.asset_disk_update, self.proxy_disk_change)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "MamManager", None, QtGui.QApplication.UnicodeUTF8))
        self.b_rushes.setText(QtGui.QApplication.translate("MainWindow", "Rushes", None, QtGui.QApplication.UnicodeUTF8))
        self.b_users.setText(QtGui.QApplication.translate("MainWindow", "Utilisateurs", None, QtGui.QApplication.UnicodeUTF8))
        self.b_clients.setText(QtGui.QApplication.translate("MainWindow", "Clients", None, QtGui.QApplication.UnicodeUTF8))
        self.b_drives.setText(QtGui.QApplication.translate("MainWindow", "Disques", None, QtGui.QApplication.UnicodeUTF8))
        self.b_progress.setText(QtGui.QApplication.translate("MainWindow", "Progression", None, QtGui.QApplication.UnicodeUTF8))
        self.label_29.setText(QtGui.QApplication.translate("MainWindow", "Collection", None, QtGui.QApplication.UnicodeUTF8))
        self.b_add_coll.setToolTip(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p>Ajouter un <span style=\" font-weight:600;\">objet</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.b_add_coll.setStatusTip(QtGui.QApplication.translate("MainWindow", "Ajouter un groupe", None, QtGui.QApplication.UnicodeUTF8))
        self.b_remove_coll.setToolTip(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p>Retirer un <span style=\" font-weight:600;\">objet</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButton.setToolTip(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p>Actualiser</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "Groupe", None, QtGui.QApplication.UnicodeUTF8))
        self.b_add_gp.setToolTip(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p>Ajouter un <span style=\" font-weight:600;\">objet</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.b_add_gp.setStatusTip(QtGui.QApplication.translate("MainWindow", "Ajouter un groupe", None, QtGui.QApplication.UnicodeUTF8))
        self.b_remove_gp.setToolTip(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p>Retirer un <span style=\" font-weight:600;\">objet</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.b_chg_coll.setToolTip(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p>Déplacer l\'objet</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.b_chg_rights.setToolTip(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p>Déplacer l\'objet</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("MainWindow", "Projet", None, QtGui.QApplication.UnicodeUTF8))
        self.b_add_project.setToolTip(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p>Ajouter un <span style=\" font-weight:600;\">objet</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.b_rmve_project.setToolTip(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p>Retirer un <span style=\" font-weight:600;\">objet</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.b_chg_gp.setToolTip(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p>Déplacer l\'objet</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("MainWindow", "Cartes", None, QtGui.QApplication.UnicodeUTF8))
        self.b_ingest.setToolTip(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p>Ajouter un <span style=\" font-weight:600;\">objet</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.b_card_rmve.setToolTip(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p>Retirer un <span style=\" font-weight:600;\">objet</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.b_card_chge.setToolTip(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p>Déplacer l\'objet</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("MainWindow", "Clips", None, QtGui.QApplication.UnicodeUTF8))
        self.label_23.setText(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Analyse de la </span></p><p align=\"center\"><span style=\" font-weight:600;\">carte</span></p><p align=\"center\">Merci de patienter...</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.b_add_proxy.setToolTip(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">Recréer les proxys</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.b_add_proxy.setText(QtGui.QApplication.translate("MainWindow", "Proxy", None, QtGui.QApplication.UnicodeUTF8))
        self.b_remove_proxy.setToolTip(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p>Supprimer les proxys</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.b_remove_proxy.setText(QtGui.QApplication.translate("MainWindow", "Proxy", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "Métadonnées :", None, QtGui.QApplication.UnicodeUTF8))
        self.b_add_user.setToolTip(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p>Ajouter un <span style=\" font-weight:600;\">objet</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.b_add_user.setStatusTip(QtGui.QApplication.translate("MainWindow", "Ajouter un groupe", None, QtGui.QApplication.UnicodeUTF8))
        self.b_remove_user.setToolTip(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p>Retirer un <span style=\" font-weight:600;\">objet</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_14.setText(QtGui.QApplication.translate("MainWindow", "Création d\'un nouvel utilisateur", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("MainWindow", "Nom de l\'utilisateur :", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("MainWindow", "Mot de passe :", None, QtGui.QApplication.UnicodeUTF8))
        self.l_user_pass1.setPlaceholderText(QtGui.QApplication.translate("MainWindow", "6 carctères minimum", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("MainWindow", "Confirmer le mot de passe :", None, QtGui.QApplication.UnicodeUTF8))
        self.l_user_pass2.setPlaceholderText(QtGui.QApplication.translate("MainWindow", "6 carctères minimum", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("MainWindow", "Type d\'utilisateur :", None, QtGui.QApplication.UnicodeUTF8))
        self.c_admin.setItemText(0, QtGui.QApplication.translate("MainWindow", "Utilisateur", None, QtGui.QApplication.UnicodeUTF8))
        self.c_admin.setItemText(1, QtGui.QApplication.translate("MainWindow", "Administrateur", None, QtGui.QApplication.UnicodeUTF8))
        self.label_48.setText(QtGui.QApplication.translate("MainWindow", "Email", None, QtGui.QApplication.UnicodeUTF8))
        self.c_masters.setText(QtGui.QApplication.translate("MainWindow", "Peut voir les masters", None, QtGui.QApplication.UnicodeUTF8))
        self.label_50.setText(QtGui.QApplication.translate("MainWindow", "Groupe suivi par défaut :", None, QtGui.QApplication.UnicodeUTF8))
        self.c_cansend.setText(QtGui.QApplication.translate("MainWindow", "Peut envoyer aux clients", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("MainWindow", "Ajouter un utilisateur en appuyant sur +", None, QtGui.QApplication.UnicodeUTF8))
        self.ch_admin.setText(QtGui.QApplication.translate("MainWindow", "Administrateur", None, QtGui.QApplication.UnicodeUTF8))
        self.label_21.setText(QtGui.QApplication.translate("MainWindow", "Mot de passe :", None, QtGui.QApplication.UnicodeUTF8))
        self.label_22.setText(QtGui.QApplication.translate("MainWindow", "Groupe suivi par défaut :", None, QtGui.QApplication.UnicodeUTF8))
        self.ch_master.setText(QtGui.QApplication.translate("MainWindow", "Peut voir les masters", None, QtGui.QApplication.UnicodeUTF8))
        self.label_20.setText(QtGui.QApplication.translate("MainWindow", "Nom de l\'utilisateur :", None, QtGui.QApplication.UnicodeUTF8))
        self.label_24.setText(QtGui.QApplication.translate("MainWindow", "Email", None, QtGui.QApplication.UnicodeUTF8))
        self.change_pass.setText(QtGui.QApplication.translate("MainWindow", "Modifier", None, QtGui.QApplication.UnicodeUTF8))
        self.ch_send.setText(QtGui.QApplication.translate("MainWindow", "Peut envoyer aux clients", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Disque de sauvegarde</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.asset_disk_name_label.setText(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p align=\"center\">Nom du disque</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.asset_disk_free_label.setText(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-style:italic;\">200 Mo disponible</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.asset_disk_online_label.setText(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-style:italic;\">Autres disques online : </span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.asset_disk_change.setText(QtGui.QApplication.translate("MainWindow", "Changer...", None, QtGui.QApplication.UnicodeUTF8))
        self.asset_disk_update.setText(QtGui.QApplication.translate("MainWindow", "Actualiser", None, QtGui.QApplication.UnicodeUTF8))
        self.label_15.setText(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Disque de proxy</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.proxy_disk_name_label.setText(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p align=\"center\">nom du disque</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.proxy_disk_free_label.setText(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-style:italic;\">2000 Mo disponible</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.proxy_disk_free_label_2.setText(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-style:italic;\"/></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.proxy_disk_change.setText(QtGui.QApplication.translate("MainWindow", "Changer...", None, QtGui.QApplication.UnicodeUTF8))
        self.label_26.setText(QtGui.QApplication.translate("MainWindow", "<b>Analyse des cartes</b>", None, QtGui.QApplication.UnicodeUTF8))
        self.lab_analyse.setText(QtGui.QApplication.translate("MainWindow", "Aucune analyse en cours...", None, QtGui.QApplication.UnicodeUTF8))
        self.label_27.setText(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">Copie des cartes</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.lab_copy.setText(QtGui.QApplication.translate("MainWindow", "Aucune copie en cours...", None, QtGui.QApplication.UnicodeUTF8))
        self.label_28.setText(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">Création des proxys</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.lab_proxy.setText(QtGui.QApplication.translate("MainWindow", "Aucune génération en cours...", None, QtGui.QApplication.UnicodeUTF8))
        self.label_42.setText(QtGui.QApplication.translate("MainWindow", "Sauvegarde des rushes : ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_49.setText(QtGui.QApplication.translate("MainWindow", "Aucune copie en cours....", None, QtGui.QApplication.UnicodeUTF8))
        self.b_add_client.setToolTip(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p>Ajouter un <span style=\" font-weight:600;\">objet</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.b_add_client.setStatusTip(QtGui.QApplication.translate("MainWindow", "Ajouter un groupe", None, QtGui.QApplication.UnicodeUTF8))
        self.b_remove_user_3.setToolTip(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p>Retirer un <span style=\" font-weight:600;\">objet</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_34.setText(QtGui.QApplication.translate("MainWindow", "Création d\'un nouveau client", None, QtGui.QApplication.UnicodeUTF8))
        self.label_37.setText(QtGui.QApplication.translate("MainWindow", "Confirmer le mot de passe :", None, QtGui.QApplication.UnicodeUTF8))
        self.label_38.setText(QtGui.QApplication.translate("MainWindow", "Email : ", None, QtGui.QApplication.UnicodeUTF8))
        self.l_client__pass1.setPlaceholderText(QtGui.QApplication.translate("MainWindow", "6 carctères minimum", None, QtGui.QApplication.UnicodeUTF8))
        self.label_35.setText(QtGui.QApplication.translate("MainWindow", "Username :", None, QtGui.QApplication.UnicodeUTF8))
        self.label_36.setText(QtGui.QApplication.translate("MainWindow", "Mot de passe :", None, QtGui.QApplication.UnicodeUTF8))
        self.l_client_pass2.setPlaceholderText(QtGui.QApplication.translate("MainWindow", "6 carctères minimum", None, QtGui.QApplication.UnicodeUTF8))
        self.label_47.setText(QtGui.QApplication.translate("MainWindow", "Groupes par défaut :", None, QtGui.QApplication.UnicodeUTF8))
        self.label_41.setText(QtGui.QApplication.translate("MainWindow", "Société :", None, QtGui.QApplication.UnicodeUTF8))
        self.label_32.setText(QtGui.QApplication.translate("MainWindow", "Nom complet : ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_40.setText(QtGui.QApplication.translate("MainWindow", "Ajouter un client en appuyant sur +", None, QtGui.QApplication.UnicodeUTF8))
        self.label_44.setText(QtGui.QApplication.translate("MainWindow", "Username :", None, QtGui.QApplication.UnicodeUTF8))
        self.label_45.setText(QtGui.QApplication.translate("MainWindow", "E-Mail", None, QtGui.QApplication.UnicodeUTF8))
        self.label_43.setText(QtGui.QApplication.translate("MainWindow", "Nouveau mot de passe :", None, QtGui.QApplication.UnicodeUTF8))
        self.label_46.setText(QtGui.QApplication.translate("MainWindow", "Groupes par défaut :", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButton_2.setText(QtGui.QApplication.translate("MainWindow", "Changer", None, QtGui.QApplication.UnicodeUTF8))
        self.label_30.setText(QtGui.QApplication.translate("MainWindow", "Nom complet :", None, QtGui.QApplication.UnicodeUTF8))
        self.label_31.setText(QtGui.QApplication.translate("MainWindow", "Socitété :", None, QtGui.QApplication.UnicodeUTF8))
        self.label_19.setText(QtGui.QApplication.translate("MainWindow", "Connexion à MamManager", None, QtGui.QApplication.UnicodeUTF8))
        self.label_17.setText(QtGui.QApplication.translate("MainWindow", "Mot de passe ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_16.setText(QtGui.QApplication.translate("MainWindow", "Nom d\'utilisateur", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButton_7.setText(QtGui.QApplication.translate("MainWindow", "Mot de passe perdu", None, QtGui.QApplication.UnicodeUTF8))
        self.b_connect.setText(QtGui.QApplication.translate("MainWindow", "Connexion", None, QtGui.QApplication.UnicodeUTF8))
        self.b_connect.setShortcut(QtGui.QApplication.translate("MainWindow", "Return", None, QtGui.QApplication.UnicodeUTF8))
        self.dbIcon.setToolTip(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p>Erreur de connexion à la base de données.</p><p>Vérifiez que vous avez bien lancé <span style=\" font-weight:600;\">MySql.</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.dbIcon.setText(QtGui.QApplication.translate("MainWindow", "Database", None, QtGui.QApplication.UnicodeUTF8))
        self.deconnect.setText(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p align=\"right\"><a href=\"http://logout\"><span style=\" text-decoration: underline; color:#0000ff;\">Déconnexion</span></a></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFichier.setTitle(QtGui.QApplication.translate("MainWindow", "Fichier", None, QtGui.QApplication.UnicodeUTF8))
        self.menuActions_de_l_administrateur.setTitle(QtGui.QApplication.translate("MainWindow", "Maintenance", None, QtGui.QApplication.UnicodeUTF8))
        self.menuOutils.setTitle(QtGui.QApplication.translate("MainWindow", "Outils", None, QtGui.QApplication.UnicodeUTF8))
        self.actionQuitter.setText(QtGui.QApplication.translate("MainWindow", "Quitter", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPurger_les_miniatures.setText(QtGui.QApplication.translate("MainWindow", "Supprimer les proxys inutiles", None, QtGui.QApplication.UnicodeUTF8))
        self.actionEchec_proxy.setText(QtGui.QApplication.translate("MainWindow", "Réparer les proxy en echec", None, QtGui.QApplication.UnicodeUTF8))
        self.sendmailToUsers.setText(QtGui.QApplication.translate("MainWindow", "Envoyer un mail à tous les utilisateurs", None, QtGui.QApplication.UnicodeUTF8))
        self.sendmailToClients.setText(QtGui.QApplication.translate("MainWindow", "Envoyer un mail à tous les clients", None, QtGui.QApplication.UnicodeUTF8))
        self.sendmailToDevel.setText(QtGui.QApplication.translate("MainWindow", "Rapporter un bug", None, QtGui.QApplication.UnicodeUTF8))

from PySide import QtWebKit
